### ISSUE TITLE
Please correct the bug before upload the code. It have many bugs

### ISSUE THREAD

**Issue by John1231983** [shreshth211/image-registration-cnn#1]
Please correct the bug before upload the code. It have many bugs. Please run in your PC first.

**Comment by kumarshreshtha** [comment]
I am sorry you had issues with the code. The code was written as part of a presentation for demonstrating the ideas of the paper. I never got the chance to complete and test it since my request for Data was never approved by the NCTN/NCORP Data Archive. I am modifying the readme file to indicate this.

**Comment by jizongFox** [comment]
Have you got the access for now?

**Comment by kumarshreshtha** [comment]
I never heard back from them but I work for a medical imaging company now so I have some data I can test this on. I'll update this repo as soon as I get some time.
