### ISSUE TITLE
Could we use your model to registration 2D image

### ISSUE THREAD

**Issue by Juddd** [shreshth211/image-registration-cnn#3]
I have an image [like this](https://user-images.githubusercontent.com/10048069/187740753-2859fe06-53b0-403a-b368-a3aa9b13c6ed.png). And I have a target image [like this](https://user-images.githubusercontent.com/10048069/187740889-343b3033-3cbf-4e67-8e18-77c35652879b.png). I want to use the empty image to register that handwriting image. Is possible? Or do you have a reliable model to introduce?

**Comment by kumarshreshtha** [comment]
You can in theory use this or any deep learning method for these images (but you'll need to retrain the model, as I doubt any DL method will work out of the box for this). However for this particular use case, I don't think you need a deep learning model at all. 

All you need is to align the 4 rectangles on the 4 corners. A simple image processing pipeline like this will do : 
- detect the 4 rectangles (let's say with template matching) 
- find the rotation angle and center of the rectangles on the source image and the target image (see [here](https://stackoverflow.com/a/44581188/5833649) on how to do it using PCA)
- get the delta in rotation angles and rotate the source to match the target rotation. Then translate the images so that the centers of the rectangles align.

(everything you need here should be available in openCV)

Closing the issue, if you have more doubts I recommend asking this question on stack overflow.
